### ISSUE TITLE
Is it safe to cache measurements across user sessions?

### ISSUE THREAD

**Issue by kristomi** [talkpython/anvil-course#1]
Hi!
in the [data_access file](https://github.com/talkpython/anvil-course/blob/master/src/anvil_app/raw_code/modules/data_access.py), you cache the measurements, but you do not clear the cache when the user logs out. Wouldn't that mean that if another user signs in on the same computer, he would get access to the cached measurements of the previous user? (The same applies to `my_ave`).

I loved the course, by the way! Anvil seems to be a lot easier to get started with than the traditional web frameworks.

**Comment by mikeckennedy** [comment]
Hi @kristomi 

That's a good catch. The answers is it _depends_. 

Remeber all of that stuff there is just a session in a tab in a browser. It will be reset / lost if you even navigate away then back (not the back button but renavigate to the page). If you're on a public computer, say in a library, and you logout, leave the page open, and another person were to log in, that would be a problem. 

Given the type of app this is, it's *extremely* unlikely. But if you're building a real app, yes, you want to think these things through! 

You should clear them on logout.

**Comment by mikeckennedy** [comment]
I updated the app that you can clone and source code with this. Thanks.
